<a href="https://colab.research.google.com/github/jaswanthmathan/project/blob/main/Jaswanth_Day08_Diy_Solution_Doc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Define a NumPy array with 4*5 dimensions, and swap the array's dimensions to
make it 5*4 using suitable functions.

In [ ]:
 import numpy as np
#transpose
arr_transposed = arr_reshaped.T
print("\nTransposed array:\n", arr_transposed)
 arr = np.arange(20)
 print("original array:\n",arr)
# reshape
arr_reshaped=arr.reshape((5,4))
print("\nReshaped array:\n", arr_reshaped)


original array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

Reshaped array:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

Transposed array:
 [[ 0  4  8 12 16]
 [ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]]


Write a Python program to create two 2-dimensional arrays and apply
hstack(), vstack(), concatenate(), and split() functions to
them to get the output as shown below.

In [ ]:
import numpy as np

# the first array
arr1 = np.array([[1, 2], [3, 4]])
print("First array is:")
print(arr1)
print()

#  the second array
arr2 = np.array([[6, 7], [8, 9]])
print("Second array is:")
print(arr2)
print()

# Applying hstack() function
arr_h = np.hstack((arr1, arr2))
print("Applying hstack() function :")
print(arr_h)
print()

# Applying vstack() function
arr_v = np.vstack((arr1, arr2))
print("Applying vstack() function :")
print(arr_v)
print()

# Applying concatenate() function
arr_concat = np.concatenate((arr1, arr2), axis=1)
print("Applying concatenate() function :")
print(arr_concat)
print()

# Applying split() function
arr_split = np.split(arr_concat, 2)
print("Applying Split () function:")
print(arr_split)










First array is:
[[1 2]
 [3 4]]

Second array is:
[[6 7]
 [8 9]]

Applying hstack() function :
[[1 2 6 7]
 [3 4 8 9]]

Applying vstack() function :
[[1 2]
 [3 4]
 [6 7]
 [8 9]]

Applying concatenate() function :
[[1 2 6 7]
 [3 4 8 9]]

Applying Split () function:
[array([[1, 2, 6, 7]]), array([[3, 4, 8, 9]])]
