<a href="https://colab.research.google.com/github/jaswanthmathan/project/blob/main/Jaswanth_Day07_Diy_Solution_doc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Write  a  Python  program  that  takes  the  speeds  of  any  vehicle  to  store  it  in  a NumPy array and calculates the average speed.Note:Use NumPy functions to get the desired output.

In [ ]:
import numpy as np

num_speeds =int (input("what number of speed you want to enter?"))
a=  int(input("Enter the speeds in Km/hr:")) 
b=  int(input("Enter the speeds in Km/hr:")) 
c=  int(input("Enter the speeds in Km/hr:")) 
d=  int(input("Enter the speeds in Km/hr:")) 
e=  int(input("Enter the speeds in Km/hr:")) 
speeds=np.array([a,b,c,d,e])
mean=np.mean(speeds)
print("The Average speed is :",mean ,"km/hr")

what number of speed you want to enter?5
Enter the speeds in Km/hr:92
Enter the speeds in Km/hr:76
Enter the speeds in Km/hr:83
Enter the speeds in Km/hr:78
Enter the speeds in Km/hr:84
The Average speed is : 82.6 km/hr


Write a Python program to generate a 3-D array with integers of your choice, perform indexing, and print the first two rows and last two columns of the array.Note: UseNumPyarange()functiontogeneratearandomarray

In [ ]:
import numpy as np

# Generate a 3D array with random integers
array= np.arange(20).reshape(5,4)
# Print the first two rows and last two columns of the array
print("the array is:")
print(array)
print("The first two rows are:")
print(array[:2,:])
print("The last two columns are:")
print(array[ :, -2:])

the array is:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
The first two rows are:
[[0 1 2 3]
 [4 5 6 7]]
The last two columns are:
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]
 [18 19]]
